### ISSUE TITLE
Support of Compose 1.7.0+

### ISSUE THREAD

**Issue by savelyevdm** [ITECOMMPAY/mobile-sdk-android-ui#7]
Hi, @AlexeyKhrameev !

Recently I tried to run your MSDK `v3.6.6` with fresh `androidx.compose.material:material:1.7.4` and caught an exception:
```
FATAL EXCEPTION: main
                 java.lang.NoSuchMethodError: No static method rememberBottomDrawerState(Landroidx/compose/material/BottomDrawerValue;Lkotlin/jvm/functions/Function1;Landroidx/compose/runtime/Composer;II)Landroidx/compose/material/BottomDrawerState; in class Landroidx/compose/material/DrawerKt; or its super classes (declaration of 'androidx.compose.material.DrawerKt' appears in /data/app/~~rY9QBWUeAh83pidfyPbU_w==/.../base.apk)
                 	at com.paymentpage.msdk.ui.presentation.MainContentKt.MainContent(MainContent.kt:54)
                 	at com.paymentpage.msdk.ui.PaymentActivity$onCreate$1.invoke(PaymentActivity.kt:82)
                 	at com.paymentpage.msdk.ui.PaymentActivity$onCreate$1.invoke(PaymentActivity.kt:76)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:441)
                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
```
This exception happens because of conflict between `androidx.compose.material:material:1.6.8` (which is base for MSDK) and `androidx.compose.material:material:1.7.4` (which is mine base).

As far as I can see you can effortlessly update your compose version to the latest one and no further action is required: I already tried, so you don't have to worry.

I can't return back to compose pre-1.7.0 (as I'm using fresh version of text inputs from 1.7.0+) - so could you, please, **update compose version inside your aar** to make it compatible again?

**Comment by savelyevdm** [comment]
@AlexeyKhrameev Thanks!
One more request to make this issue really closed: add, please, core version 0.12.2 to maven. As of now we get an exception with 3.7.0:
```
Failed to resolve: com.ecommpay:msdk-core-android:0.12.2
```
