### ISSUE TITLE
Android 7.1: java.lang.NoClassDefFoundError in SdkExpiry.isMoreThanNow()

### ISSUE THREAD

**Issue by savelyevdm** [ITECOMMPAY/mobile-sdk-android-ui#8]
Hi, @AlexeyKhrameev !

Some time ago we noticed a bug on Android 7.1:
```
                 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
                     at kotlinx.datetime.Instant.<clinit>(Instant.kt:96)
                     at kotlinx.datetime.Clock$System.now(Clock.kt:25)
                     at com.paymentpage.msdk.core.domain.entities.SdkExpiry.isMoreThanNow(SdkExpiry.kt:57)
```

Looks like Android 7.1 doesn't know about `kotlinx.datetime.Instant`. This issue can be fixed using [Java 8+ API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring), but it'll be better to fix natively in MSDK.

Would be great, if you can fix it! 😊

**Comment by AlexeyKhrameev** [comment]
fixed at 3.7.0
